import { useState, type CSSProperties } from 'react';
import { ArrowLeft, ArrowUpRight, Backpack, BookOpen, Compass, Heart, Map, Tent, Zap } from 'lucide-react';
import { expeditionBagCount, expeditionProducts, expeditionRoutes, getRegionUnlocked, projectIds, regionIds, regions } from '../core/expeditionData';
import { getBaseUpgrade, getExpeditionHarvestLeft, getExpeditionStartReason, isExpeditionSupply, startExpedition, upgradeExpeditionBase } from '../core/expedition';
import { communityProjects } from '../core/expeditionProjects';
import { getInventoryItem } from '../core/items';
import { getPetEnergyCap, getPetStatCap } from '../core/petStats';
import { canSpendCompanionTime } from '../core/kitchen';
import { ExpeditionJourney } from './expedition/ExpeditionJourney';
import { ExpeditionProjects } from './expedition/ExpeditionProjects';
import type { ExpeditionProps } from './expedition/types';
import type { Inventory, ItemId } from '../core/petTypes';
import type { RegionId } from '../core/expeditionTypes';
import '../styles/expedition.css';

export const ExpeditionMap = ({ selected, pet, onSelect }: { selected: RegionId; pet: ExpeditionProps['pet']; onSelect: (id: RegionId) => void }) => {
  const points = [[21, 74], [40, 43], [18, 19], [73, 71], [79, 21]];
  return <div className="exp-map" aria-label="五地区地图"><svg viewBox="0 0 600 340" aria-hidden="true"><defs><pattern id="exp-grid" width="26" height="26" patternUnits="userSpaceOnUse"><path d="M26 0H0V26" fill="none" stroke="#d7dfcc" strokeWidth=".7" /></pattern></defs><rect width="600" height="340" fill="#e8eddd" /><rect width="600" height="340" fill="url(#exp-grid)" /><path d="M370 340Q340 260 393 221T530 160L600 187V340" fill="#b7d4cf" /><path d="M0 279Q93 177 184 228T350 219L421 340H0Z" fill="#cbd9ba" /><path d="M310 0L376 78L445 4L511 79L564 0" fill="#d0d6c1" /><path d="M126 252L240 146L108 65M240 146L438 241L474 71M108 65L474 71" fill="none" stroke="#fefcf1" strokeWidth="9" strokeLinecap="round"/><path d="M126 252L240 146L108 65M240 146L438 241L474 71M108 65L474 71" fill="none" stroke="#a5b49b" strokeWidth="2" strokeDasharray="5 7"/><g fill="#799679"><path d="M48 124L61 92L74 124ZM76 130L89 98L102 130ZM30 145L43 113L56 145Z"/><path d="M276 292L289 260L302 292ZM300 305L313 273L326 305Z"/></g><g fill="#f8f7e7"><circle cx="326" cy="110" r="7"/><circle cx="335" cy="100" r="9"/><circle cx="349" cy="111" r="8"/></g><text x="544" y="290" fill="#6f9291" fontSize="10" letterSpacing="3">潮 汐 湾</text><path d="M552 31V65M540 47H564" stroke="#758a79" strokeWidth="1.5"/><text x="548" y="24" fontSize="10" fill="#758a79">N</text></svg>
    {regionIds.map((id, i) => <button key={id} style={{ left: `${points[i][0]}%`, top: `${points[i][1]}%`, '--region-color': regions[id].color } as CSSProperties} aria-label={`查看${regions[id].name}${getRegionUnlocked(pet, id) ? '' : '，尚未开放'}`} aria-pressed={selected === id} data-locked={!getRegionUnlocked(pet, id)} onClick={() => onSelect(id)}><span>{regions[id].glyph}</span><b>{regions[id].name}</b><small>{pet.community.expedition.regions[id].base ? '⌂ 已建基地' : pet.community.expedition.regions[id].surveyed ? '✓ 已勘测' : getRegionUnlocked(pet, id) ? '等待发现' : '未开放'}</small></button>)}
  </div>;
};
export const ExpeditionPage = (props: ExpeditionProps & { initialTab?: 'map' | 'projects' | 'journal' }) => {
  const { pet, portrait, update, actorId, actorName, onCommunity, onKitchen, onShop } = props, s = pet.community.expedition;
  const [tab, setTab] = useState<'map' | 'projects' | 'journal'>(props.initialTab ?? 'map');
  const [selected, setSelected] = useState<RegionId>(s.regions.hills.surveyed && !s.regions.forest.surveyed ? 'forest' : 'valley');
  const [mode, setMode] = useState<'manual' | 'idle'>('manual'), [parts, setParts] = useState(1), [routeId, setRouteId] = useState('single');
  const [bag, setBag] = useState<Inventory>({}), [tool, setTool] = useState(false);
  const r = regions[selected], progress = s.regions[selected], cap = getPetStatCap(pet), unlocked = getRegionUnlocked(pet, selected), upgrade = getBaseUpgrade(progress.base);
  const route = mode === 'idle' || routeId === 'single' ? [selected] : expeditionRoutes.find(route => route.id === routeId)!.regions;
  const startReason = getExpeditionStartReason(pet, route, mode, parts), count = expeditionBagCount(bag);
  const invalidBag = count > 12 || Object.entries(bag).some(([id, n]) => n > (pet.inventory[id] ?? 0)) || tool && !(pet.inventory.trail_rope ?? 0);
  const active = Boolean(s.active || s.pending), surveyed = regionIds.filter(id => s.regions[id].surveyed).length;
  const chooseRegion = (id: RegionId) => { setSelected(id); setRouteId('single'); };
  const recommend = () => { const meal = (['dish_mushroom_rice', 'dish_kelp_rice', 'trail_mix', 'dish_carrot_rice'] as const).find(id => (pet.inventory[id] ?? 0) > 0); setBag({ ...(meal ? { [meal]: Math.min(2, pet.inventory[meal] ?? 0) } : {}), ...((pet.inventory.field_dressing ?? 0) > 0 ? { field_dressing: Math.min(2, pet.inventory.field_dressing ?? 0) } : {}) }); setTool((pet.inventory.trail_rope ?? 0) > 0); };
  const health = Math.round(pet.health / cap * 100);
  return <section className="exp-page"><header className="exp-header"><button className="exp-back" aria-label="返回溪畔社区" onClick={onCommunity}><ArrowLeft size={19} /></button><div><small>POCKET / A LITTLE FURTHER</small><h1>社区与远方</h1></div><div className="exp-wallet"><span>🪙 {pet.coins}</span><span>♡ {pet.hearts}</span></div></header>
    <nav className="exp-tabs" aria-label="远征页面">{([['map', Map, '去远方'], ['projects', Tent, '社区项目'], ['journal', BookOpen, '旅行手账']] as const).map(([id, Icon, label]) => <button key={id} aria-current={tab === id ? 'page' : undefined} onClick={() => setTab(id)}><Icon size={17} />{label}{id === 'projects' && projectIds.some(id => s.projects[id].theme) && <i />}</button>)}<button onClick={onCommunity}>回到社区 <ArrowUpRight size={15} /></button></nav>
    <div className="exp-vitals" aria-label="伙伴状态">{[['饱食', pet.hunger, cap], ['体力', pet.energy, getPetEnergyCap(pet)], ['心情', pet.mood, cap], ['健康', pet.health, cap]].map(([label, value, max]) => <div key={label} data-warning={label === '健康' && health < 35}><span>{label}<b>{Math.floor(Number(value))}<small>/{max}</small></b></span><progress max={Number(max)} value={Number(value)} /></div>)}<div className="exp-health-note"><Heart size={15} /><span>健康 {health}%<small>低于 20% 安全返程</small></span></div></div>
    <p className="exp-event" role="status">{pet.recentEvent}</p>
    {active && <ExpeditionJourney key={s.active?.id ?? s.pending?.id} {...props} />}
    {tab === 'projects' ? <ExpeditionProjects {...props} /> : tab === 'journal' ? <><div className="exp-section-intro"><small>物品用掉了，故事还留在这里</small><h2>我们一起走过的地方。</h2><p>地区故事 {surveyed}/5 · 社区回忆 {projectIds.filter(id => s.projects[id].completed).length}/3 · 首次成果累计体力上限 +{surveyed * 2 + projectIds.filter(id => s.projects[id].completed).length * 3}</p></div><div className="exp-journal-grid">{regionIds.map(id => <article key={id} className="exp-card" data-unknown={!s.regions[id].surveyed}><span className="exp-icon">{regions[id].glyph}</span><h3>{regions[id].story}</h3><p>{s.regions[id].surveyed ? regions[id].storyText : '故事还没翻到这一页。'}</p><small>{s.regions[id].surveyed ? `和${s.regions[id].actorName || actorName} · ${s.regions[id].storyAt ? new Date(s.regions[id].storyAt!).toLocaleDateString('zh-CN') : '已记录'}` : regions[id].unlockHint}</small></article>)}{projectIds.filter(id => s.projects[id].completed).map(id => <article key={id} className="exp-card"><span className="exp-icon">✧</span><h3>{communityProjects[id].memory}</h3><p>和{s.projects[id].actorName || actorName}一起，为{communityProjects[id].name}留下的第一页回忆。</p><small>已经举办 {s.projects[id].completed} 次 · 首次成长永久保留</small></article>)}</div><section className="exp-card exp-collection"><h3>地区物产小册</h3><div>{Object.entries(expeditionProducts).map(([id, product]) => <article key={id}><span>{product.glyph}</span><div><b>{product.name}</b><small>{product.use}</small><small>已发现 {s.collection[id as keyof typeof expeditionProducts] ?? 0} · 仓库 {pet.inventory[id] ?? 0}</small></div></article>)}</div></section></> : <>
      <div className="exp-hero"><div className="exp-hero-copy"><span className="exp-eyebrow">从一处发现，到一桌好生活</span><h2>走远一点，<br />让日常多一点惊喜。</h2><p>去花田找蜂蜜，在林地留一袋种子。带着新滋味回来，邀邻居一起坐坐。</p><div className="exp-hero-footer"><img src={portrait} alt={actorName} /><span>今天和{actorName}一起<small>已探索 {surveyed} / 5 个地区</small></span><Compass size={30} /></div></div><ExpeditionMap selected={selected} pet={pet} onSelect={chooseRegion} /></div>
      <div className="exp-region-tabs" aria-label="选择地区">{regionIds.map(id => <button key={id} aria-pressed={selected === id} onClick={() => chooseRegion(id)}>{regions[id].glyph} {regions[id].name}<small>{s.regions[id].surveyed ? '已勘测' : getRegionUnlocked(pet, id) ? '可探索' : '待开放'}</small></button>)}</div>
      <div className="exp-layout"><main className="exp-stack"><article className="exp-card exp-destination" style={{ '--region-color': r.color } as CSSProperties}><div className="exp-card-heading"><span className="exp-icon">{r.glyph}</span><div><small>{r.subtitle}</small><h2>{r.name}</h2></div><span className="exp-badge">{progress.surveyed ? '已勘测 · 可回访' : '地区故事'}</span></div><p>{progress.surveyed ? r.storyText : `这一趟的目标：${r.story}。${selected === 'hills' ? '完成后，林地与海岸可以自由选择。' : ''}`}</p><div className="exp-product-row">{[...new Set([r.product, r.alternative])].map(id => <div key={id}><span>{expeditionProducts[id].glyph}</span><b>{expeditionProducts[id].name}</b><small>{expeditionProducts[id].use}</small></div>)}</div><div className="exp-destination-foot"><span>今日采集 {getExpeditionHarvestLeft(pet, selected)}/3 次<small>凌晨 5 点刷新 · 手动与挂机共用</small></span>{r.recipe && <button onClick={() => onKitchen(r.recipe)}>查看当地料理 →</button>}</div></article>
        {!active && <section className="exp-card exp-preparation"><div className="exp-card-heading"><Backpack size={21} /><h3>准备这一趟</h3></div><div className="exp-theme"><button aria-pressed={mode === 'manual'} onClick={() => setMode('manual')}>亲自探索</button><button aria-pressed={mode === 'idle'} onClick={() => setMode('idle')}>挂机远行</button></div>
          {mode === 'manual' ? <><label className="exp-select-label">行程<select aria-label="选择远征行程" value={routeId} onChange={e => setRouteId(e.target.value)}><option value="single">只去{r.name} · 3 个手动节点</option>{expeditionRoutes.map(route => <option key={route.id} value={route.id}>{route.name} · 3 个地区</option>)}</select></label><p className="exp-route-plan">{route.map(id => regions[id].name).join(' → ')}<small>{route.length > 1 ? '途中基地可暂停，之后继续；行囊总共 12 份。' : '安全通路约消耗饱食 12、体力 14；绳索或捷径可省 4 体力。'}</small></p><details className="exp-bag" open><summary>补给 {count}/12 份 <span>工具另计</span></summary><button className="exp-link-button" onClick={recommend}>装入推荐补给</button><div className="exp-stock-list">{Object.entries(pet.inventory).filter(([id, n]) => n > 0 && isExpeditionSupply(id)).map(([id, n]) => <label key={id}><span>{getInventoryItem(id as ItemId)?.name ?? id}<small>仓库 {n}</small></span><input aria-label={`携带${getInventoryItem(id as ItemId)?.name ?? id}`} type="number" min={0} max={Math.min(12, n)} value={bag[id] ?? 0} onChange={e => { const amount = Math.max(0, Math.min(n, 12, Math.floor(Number(e.target.value)) || 0)); setBag(old => { const next = { ...old }; if (amount) next[id] = amount; else delete next[id]; return next; }); }} /></label>)}</div><label className="exp-rope"><input type="checkbox" checked={tool} disabled={!(pet.inventory.trail_rope ?? 0)} onChange={e => setTool(e.target.checked)} />携带探路绳 · 可重复用，安全通路省体力</label></details></> : <><label className="exp-select-label">远行时长<select value={parts} onChange={e => setParts(Number(e.target.value))}><option value={1}>1 小时 · 产物 ×1</option><option value={3}>3 小时 · 产物 ×3</option></select></label><div className="exp-quote"><b>出发投入</b><span>便携坚果包 ×{parts === 1 ? 1 : 2} · 饱食 −{parts === 1 ? 8 : 14} · 体力 −{parts === 1 ? 8 : 16}</span><b>带回收获</b><span>{expeditionProducts[r.product].name} ×{parts}；只走已勘测、已建基地的路线。</span></div><p>每满一小时完成一份。提前召回保留已完成收获，投入与预留的 {parts} 次今日额度不返还；不自动重开。</p></>}
          {startReason && <p className="exp-warning">{startReason}</p>}{mode === 'manual' && invalidBag && <p className="exp-warning">请调整补给数量，最多 12 份且不能超过实际库存。</p>}
          <button className="exp-primary exp-start" disabled={Boolean(startReason) || mode === 'manual' && invalidBag} onClick={() => update(p => startExpedition(p, route, mode === 'manual' ? bag : {}, mode === 'manual' && tool, actorId, actorName, mode, parts))}><Compass size={18} />{mode === 'manual' ? '和伙伴一起出发' : '准备口粮，开始远行'}<ArrowUpRight size={18} /></button><small className="exp-muted">出发健康需 ≥40%。途中随时可以返回，已发现的故事不会丢失。</small></section>}
      </main><aside className="exp-stack"><section className="exp-card exp-next"><span className="exp-eyebrow">今天做一件小事就好</span><h3>{progress.surveyed ? '把收获变成一场相聚' : `先记下${r.name}的故事`}</h3><p>{progress.surveyed ? '社区项目分阶段准备，不会过期。选择喜欢的供货主题，用已有库存也可以。' : '走完三个节点，永久开放当地配方与基地建设。普通安全通路始终可走。'}</p><button className="exp-secondary" onClick={() => setTab('projects')}>看看邻居的新计划 <ArrowUpRight size={16} /></button></section>
        <section className="exp-card"><div className="exp-card-heading"><Tent size={20} /><h3>{r.base}</h3></div><p>{progress.base === 2 ? '休息基地与往返步道都已修好。回访免费，已建成果不会离线损坏。' : progress.surveyed ? upgrade.benefit : '完成当地故事后开放建设。可以直接回访，不必重跑整条路线。'}</p>{progress.base < 2 && <><div className="exp-quote"><span>{upgrade.coins} 金币 · 木料 {upgrade.wood} · 石料 {upgrade.stone}</span></div><button className="exp-secondary" disabled={!unlocked || !progress.surveyed || !canSpendCompanionTime(pet) || pet.coins < upgrade.coins || (pet.inventory.community_wood ?? 0) < upgrade.wood || (pet.inventory.community_stone ?? 0) < upgrade.stone} onClick={() => update(p => upgradeExpeditionBase(p, selected, progress.base))}>{upgrade.name}</button></>}<small className="exp-muted">休整每趟每地一次。回访本身不发资源或通关奖励。</small></section>
        <section className="exp-card exp-notes"><Zap size={20} /><h3>每次成长，都留得住</h3><p>首次地区故事 +2 体力上限，首次社区项目 +3。补满需要休息，重复举办不再叠加上限。</p><button className="exp-link-button" onClick={() => setTab('journal')}>翻开旅行手账 →</button><button className="exp-link-button" onClick={onShop}>补充口粮与护理 →</button></section>
      </aside></div>
    </>}
  </section>;
};
