import { useState } from 'react';
import { ArrowLeft, Check, ChevronRight, Lock, Landmark, BookOpen, Palette, Sparkles, Trophy } from 'lucide-react';
import { currencyIcon } from '../assets';
import { museumImages } from '../museumAssets';
import { acceptMuseumQuest, changeMuseumAppearance, getMuseumAppearance, getMuseumExhibits, getMuseumHallReason, getMuseumOpenHalls, isClassicEndgameComplete } from '../core/pet';
import { museumHalls, museumQuests, museumQuestIds, museumRegions, museumVisits, museumVisitIds, type MuseumRegion, type MuseumVisitId } from '../core/museumData';
import { getMuseumVisitReason } from '../core/museumJourney';
import type { MuseumAppearance } from '../core/museumTypes';
import type { RecipeId } from '../core/companionActivityTypes';
import { DialogScope } from './DialogShell';
import { MuseumHall } from './museum/MuseumHall';
import { MuseumCuration } from './museum/MuseumCuration';
import { MuseumAlbum } from './museum/MuseumAlbum';
import { MuseumScene, MuseumTrophy, museumExhibitImage, type MuseumProps } from './museum/MuseumShared';
import { formatInteger } from './numberFormat';
import '../styles/museum.css';

interface Props extends MuseumProps { onBack: () => void; backLabel?: string; onVisit: (id: MuseumVisitId) => void; onExplore: (region: MuseumRegion) => void; onKitchen: (recipe?: RecipeId) => void; onFarm: () => void; onFishing: () => void; onLegacy: () => void }
type MuseumTab = 'halls' | 'quests' | 'curation' | 'album' | 'trophy';
export const MuseumPage = (props: Props) => {
  const { pet, icons, portrait, update } = props;
  const [tab, setTab] = useState<MuseumTab>('halls'), [hall, setHall] = useState<MuseumRegion>(), [questRegion, setQuestRegion] = useState<MuseumRegion | ''>('');
  const unlocked = isClassicEndgameComplete(pet), owned = getMuseumExhibits(pet.museum), opened = getMuseumOpenHalls(pet.museum);
  const appearance = getMuseumAppearance(pet), level = pet.classicEndgame.legacyLevel;
  const dress = (changes: Partial<MuseumAppearance>) => update(p => changeMuseumAppearance(p, { ...p.museum.appearance, ...changes }));
  const tabs: { id: MuseumTab; name: string; icon: typeof Landmark }[] = [{ id: 'halls', name: '展厅', icon: Landmark }, { id: 'quests', name: '委托', icon: BookOpen }, { id: 'curation', name: '策展', icon: Sparkles }, { id: 'album', name: '纪念册', icon: Palette }, { id: 'trophy', name: '奖杯装扮', icon: Trophy }];
  return <DialogScope><section className="museum-page" aria-labelledby="museum-title"><header className="museum-header"><button className="icon-button" aria-label={props.backLabel ?? '返回共同梦想'} onClick={props.onBack}><ArrowLeft /></button><div><small>一起走过的地方，都值得留下</small><h1 id="museum-title">我们的纪念馆</h1></div></header><div className="museum-wallet"><span><img src={currencyIcon} alt="金币" />{formatInteger(pet.coins)}</span><span><img src={icons.golden_apple} alt="金苹果" />{formatInteger(pet.inventory.golden_apple ?? 0)}</span><span>策展 {formatInteger(pet.museum.stars)} 星</span></div>
    {!unlocked ? <section className="museum-card"><Lock /><h2>共同梦想之后的故事</h2><p>完成四条共同梦想，获得钻石友谊奖杯后，来这里建设五地区纪念馆。</p></section> : <>
      <nav className="museum-tabs" aria-label="纪念馆导航">{tabs.map(({ id, name, icon: Icon }) => <button key={id} type="button" aria-pressed={tab === id} onClick={() => setTab(id)}><Icon size={18} /><span>{name}</span></button>)}</nav>
      <p className="museum-feedback" role="status">{pet.recentEvent}</p>
      {tab === 'halls' && <><MuseumScene icons={icons} portrait={portrait} caption={`已开馆 ${opened.length} / 5 · 永久收藏 ${owned.length} / 25 件`} /><div className="museum-section-heading"><h2>五地区展厅</h2><span>自己选择下一段纪念</span></div><div className="museum-hall-grid">{museumRegions.map(region => { const progress = pet.museum.halls[region], def = museumHalls[region], reason = getMuseumHallReason(pet, region); return <button className={`museum-hall-card${reason ? ' is-locked' : ''}`} key={region} onClick={() => setHall(region)}><img src={museumImages[def.scene]} alt="" /><span className="museum-hall-copy"><strong>{def.name}<ChevronRight size={18} /></strong><span>{progress.stage === 3 ? '正式开放 · 开馆纪念已收藏' : reason || `建设进度 ${progress.stage} / 3`}</span><small>{formatInteger(def.coins)} 金币＋{def.apples} 金苹果</small></span></button>; })}</div><section className="museum-card"><h3>每段旅途，都能成为展品</h3><p>整理展厅后接取当地委托。建设和委托共收藏 25 件展品，任意一馆正式开放后就能反复举办主题展。</p><button className="secondary-button" onClick={() => setTab(opened.length ? 'curation' : 'quests')}>{opened.length ? '筹备一场展览' : '看看地区委托'}</button></section></>}
      {tab === 'quests' && <><div className="museum-section-heading"><h2>地区委托</h2><label>地区<select value={questRegion} onChange={e => setQuestRegion(e.target.value as MuseumRegion | '')}><option value="">全部地区</option>{museumRegions.map(r => <option key={r} value={r}>{museumHalls[r].name}</option>)}</select></label></div><p>第一阶段建好后可以接取。记录接取后的行动，不限时、不清零；除夜餐交付外，成果都留在仓库。</p><div className="museum-quest-grid">{museumQuestIds.filter(id => !questRegion || museumQuests[id].region === questRegion).map(id => {
        const def = museumQuests[id], state = pet.museum.quests[id], canAccept = pet.museum.halls[def.region].stage >= 1;
        const visits = museumVisitIds.filter(v => museumVisits[v].quest === id);
        return <article key={id} className="museum-card museum-quest"><div className="museum-quest-heading"><img src={museumExhibitImage(def.exhibit, icons)} alt="委托收藏奖励" /><div><small>{museumHalls[def.region].name}</small><h3>{def.title}</h3>{state?.completedAt && <span className="is-ready"><Check size={14} />已完成 · 展品永久收藏</span>}</div></div><ul>{def.objectives.map(g => <li key={g.key} className={(state?.progress[g.key] ?? 0) >= g.amount ? 'is-ready' : ''}><span>{g.label}</span><strong>{state?.progress[g.key] ?? 0} / {g.amount}</strong></li>)}</ul>{!state ? <button className="primary-button" disabled={Boolean(pet.timePause) || !canAccept} onClick={() => update(p => acceptMuseumQuest(p, id))}>{canAccept ? '接下这项委托' : '先完成展厅第一阶段'}</button> : !state.completedAt && <div className="museum-quest-actions">{visits.map(v => { const reason = getMuseumVisitReason(pet, v); return <div key={v}><button className="primary-button" disabled={Boolean(pet.timePause) || Boolean(reason)} onClick={() => props.onVisit(v)}>去{museumVisits[v].title}</button>{reason && <small>{reason}</small>}</div>; })}{def.objectives.some(g => g.key.startsWith('gather:') || g.key.startsWith('research:')) && <button className="secondary-button" onClick={() => props.onExplore(def.region)}>去当地采集与研究</button>}{def.objectives.some(g => g.key.startsWith('cook:')) && <button className="secondary-button" onClick={() => props.onKitchen(def.objectives.find(g => g.key.startsWith('cook:'))!.key.slice(5) as RecipeId)}>去厨房准备</button>}{id === 'valley_kitchen' && <button className="secondary-button" onClick={props.onFarm}>去农场收获</button>}{id === 'forest_fish' && <button className="secondary-button" onClick={props.onFishing}>去钓鱼小屋</button>}{id === 'station_dinner' && <button className="secondary-button" onClick={() => props.onKitchen()}>准备三类夜餐</button>}</div>}</article>;
      })}</div></>}
      {tab === 'curation' && <MuseumCuration {...props} />}
      {tab === 'album' && <MuseumAlbum {...props} />}
      {tab === 'trophy' && <section className="museum-card"><MuseumTrophy pet={pet} /><button className="secondary-button" onClick={props.onLegacy}>继续提升共同纪念等级</button><div className="museum-appearance"><label>奖杯底座<select value={appearance.base} onChange={e => dress({ base: e.target.value as MuseumAppearance['base'] })}><option value="none">原始奖杯</option><option value="common" disabled={level < 1}>纪念底座 · Lv.1</option><option value="prestige" disabled={level < 20}>典藏底座 · Lv.20</option></select></label><label>纪念铭牌<select value={appearance.plate} onChange={e => dress({ plate: Number(e.target.value) as MuseumAppearance['plate'] })}>{[0, 3, 30, 50, 100].map(n => <option value={n} key={n} disabled={level < n}>{n ? `${n === 3 ? '共同纪念' : n === 30 ? '同行纪念人' : n === 50 ? '珍藏守望者' : '百阶同行'} · Lv.${n}` : '不显示铭牌'}</option>)}</select></label>{([['filigree', '花纹', 6], ['ribbon', '缎带', 9], ['crown', '冠饰', 12]] as const).map(([key, label, required]) => <label className="museum-check" key={key}><input type="checkbox" checked={appearance[key]} disabled={level < required} onChange={e => dress({ [key]: e.target.checked })} />{label} · Lv.{required}</label>)}<label>纪念册边框<select value={appearance.frame} onChange={e => dress({ frame: e.target.value as MuseumAppearance['frame'] })}><option value="none">不使用边框</option><option value="common" disabled={!pet.museum.hosted}>普通边框 · 首次举办</option><option value="prestige" disabled={pet.museum.stars < 90}>典藏边框 · 90 星</option></select></label><label>编号徽章样式<select value={appearance.badge} onChange={e => dress({ badge: e.target.value as MuseumAppearance['badge'] })}><option value="common">普通纪念徽章</option><option value="prestige" disabled={pet.museum.stars < 300}>典藏纪念徽章 · 300 星</option></select></label><label>展示称号<select value={appearance.title} onChange={e => dress({ title: e.target.value as MuseumAppearance['title'] })}><option value="default">我们的纪念馆</option><option value="companion" disabled={level < 30}>同行纪念人 · Lv.30</option><option value="keeper" disabled={level < 50}>珍藏守望者 · Lv.50</option><option value="century" disabled={level < 100}>百阶同行 · Lv.100</option><option value="curator" disabled={pet.museum.stars < 900}>长伴策展家 · 900 星</option></select></label></div><p>每 30 星收藏一枚编号徽章；900 星获得“长伴策展家”称号。纪念外观永久保留，可以随时换回喜欢的搭配。</p></section>}
    </>}
    {hall && <MuseumHall {...props} region={hall} onClose={() => setHall(undefined)} onQuests={() => { setQuestRegion(hall); setTab('quests'); setHall(undefined); }} />}
  </section></DialogScope>;
};
