import { acceptCommunityTask, cancelCommunityTask, canClaimCommunityTask, claimCommunityTask, commissionDefinitions, getCommunityCandidates, getCommunityDay, getCommunityTasks } from '../../core/communityCommissions';
import type { CommunityTask, WaterId } from '../../core/communityTypes';
import type { ItemId } from '../../core/petTypes';
import { getInventoryItem } from '../../core/items';
import type { CommunityPanelProps } from './types';

export const CommunityBoard = ({ pet, update, onExplore, onKitchen, onFishing, onFarm, registry }: CommunityPanelProps & { onFishing: (water?: WaterId) => void; onFarm?: (place: 'field' | 'coop' | 'barn') => void }) => {
  const tasks = getCommunityTasks(pet), candidates = getCommunityCandidates(pet), day = getCommunityDay(pet), accepted = pet.community.boardDay === day ? pet.community.acceptedToday : [];
  const card = (task: CommunityTask, active: boolean) => {
    const def = commissionDefinitions[task.template], used = accepted.includes(task.id), sameKind = tasks.some(t => t.template === task.template);
    return <section className="community-card community-task" key={task.id}><div className="community-section-heading"><h3>{def.name}</h3><span className="community-tag">{active ? '已接取 · 不过期' : used ? '今日已接过' : '今日候选'}</span></div><p>{def.detail}</p><p className="community-muted">酬谢：{def.coins} 金币{def.reward ? ' · 木料 ×1 · 石料 ×1' : ''}</p>
      {active ? <>{def.event && <p className="community-note">{task.found ? '✓ 已记录有效行动' : '○ 等待接取后的有效行动'}</p>}{Object.entries(def.take ?? {}).map(([id, n]) => <p key={id}>交付 {registry?.get(id)?.name ?? getInventoryItem(id as ItemId)?.name ?? id} ×{n} · 持有 {pet.inventory[id] ?? 0}</p>)}<div className="community-actions"><button className="primary-button" disabled={!canClaimCommunityTask(pet, task) || Boolean(pet.adventure.active || pet.community.expedition.active || pet.community.fishing.active)} onClick={() => update(p => claimCommunityTask(p, task.id))}>交付并领取酬谢</button>{!task.found && ['search', 'forage', 'delivery'].includes(task.template) && <button className="secondary-button" disabled={Boolean(pet.adventure.active || pet.adventure.pending || pet.community.fishing.active)} onClick={() => onExplore('commission')}>去溪谷短途{task.template === 'delivery' ? '送餐' : '搜寻'}</button>}{!task.found && task.template.startsWith('fish_') && <button className="secondary-button" onClick={() => onFishing(task.template === 'fish_upstream' ? 'upstream' : 'pond')}>去对应水域钓鱼</button>}{onFarm && ['vegetables', 'eggs', 'milk'].includes(task.template) && <button className="secondary-button" onClick={() => onFarm(task.template === 'eggs' ? 'coop' : task.template === 'milk' ? 'barn' : 'field')}>去生产地点</button>}{(task.template === 'soup' || task.template === 'fresh_porridge') && <button className="secondary-button" onClick={() => onKitchen(task.template === 'soup' ? 'creek_fish_soup' : 'herb_porridge')}>去厨房</button>}</div><details className="community-abandon"><summary>放弃这份委托</summary><p>已接取额度不会退还，已消耗的送达物不会返还。</p><button className="text-button" onClick={() => update(p => cancelCommunityTask(p, task.id))}>确认放弃</button></details></>
        : <button className="secondary-button" disabled={used || accepted.length >= 2 || tasks.length >= 2 || sameKind} onClick={() => update(p => acceptCommunityTask(p, task.id))}>{used ? '今天已接取，明日再来' : sameKind ? '先完成同类在途委托' : accepted.length >= 2 ? '今日已接满 2 单' : tasks.length >= 2 ? '先完成手上的 2 单' : '接下这份委托'}</button>}
    </section>;
  };
  return <><section className="community-card"><h3>社区公告板</h3><p>每日 5 点换新 3 个候选，最多接 2 单；同时保留 2 单。已接委托跨日不过期，次日补交不会扣新一天的接取额度。建设线索有常驻入口。</p><div className="community-note">今日已接 {accepted.length}/2 · 进行中 {tasks.length}/2</div></section>{tasks.map(task => card(task, true))}<h3 className="community-subheading">今日可以帮忙的事</h3>{candidates.length ? candidates.filter(task => !tasks.some(active => active.id === task.id)).map(task => card(task, false)) : <p className="community-note">完成踩点教学后，公告板开始发布委托。</p>}</>;
};
