import { useMemo, useState } from 'react';
import { Check, Star } from 'lucide-react';
import { beginMuseumCuration, cancelMuseumCuration, editMuseumCuration, getMuseumAvailableDishes, getMuseumCurationQuote, getMuseumEligibleThemes, getMuseumExhibits, getMuseumOpenHalls, hostMuseumCuration } from '../../core/pet';
import { museumScales, museumThemes, museumTagNames, type MuseumScale } from '../../core/museumData';
import { dishName } from '../../core/kitchenRecipes';
import { getNeighborIdentities } from '../../core/neighbors';
import { DialogShell } from '../DialogShell';
import { formatInteger } from '../numberFormat';
import { museumExhibitImage, type MuseumProps } from './MuseumShared';

export const MuseumCuration = ({ pet, icons, actorId, actorName, mods, update }: MuseumProps) => {
  const [confirm, setConfirm] = useState(false), [filter, setFilter] = useState('');
  const owned = getMuseumExhibits(pet.museum), dishes = getMuseumAvailableDishes(pet);
  const eligibilityKey = owned.map(e => e.id).join(',') + '|' + dishes.map(d => d.id).join(',') + '|' + getMuseumOpenHalls(pet.museum).join(',');
  const eligible = useMemo(() => getMuseumEligibleThemes(pet), [eligibilityKey]);
  const draft = pet.museum.draft, quote = getMuseumCurationQuote(pet);
  const filteredDishes = dishes.filter(d => dishName(d.id).includes(filter));
  const change = (value: Parameters<typeof editMuseumCuration>[3]) => { if (draft) update(p => editMuseumCuration(p, draft.id, draft.revision, value)); setConfirm(false); };
  if (!getMuseumOpenHalls(pet.museum).length) return <section className="museum-card"><h2>第一场展览正在等你</h2><p>先正式开放任意一座展厅，就能邀请邻居来参观。每场使用三件展品和两种料理。</p></section>;
  return <section className="museum-curation">
    {!draft ? <><div className="museum-section-heading"><h2>本周邀请</h2><span>{pet.museum.board.week} 起</span></div><p>每周一凌晨 5 点轮换。完成后仍可加办，每次都支付完整费用；收藏与星数永久保留。</p><div className="museum-theme-grid">{pet.museum.board.themes.map(id => <article className="museum-card" key={id}><small>本周推荐</small><h3>{museumThemes[id].name}</h3><ul>{museumThemes[id].goals.map(g => <li key={g}>{g}</li>)}</ul><button className="primary-button" disabled={Boolean(pet.timePause) || !eligible.includes(id)} onClick={() => update(p => beginMuseumCuration(p, id))}>筹备展览</button></article>)}</div>{!pet.museum.board.themes.length && <p>本周还没有适合的邀请，可以继续收集展品、解锁料理，并从下方选择可举办的主题。</p>}
      <h3>自由举办</h3><div className="museum-theme-grid">{Object.entries(museumThemes).map(([key, def]) => { const id = key as keyof typeof museumThemes, available = eligible.includes(id); return <article className={`museum-card${available ? '' : ' is-locked'}`} key={id}><h4>{def.name}</h4><p>{pet.museum.best[id] ? `最佳评分 ${pet.museum.best[id]!.rating} 星` : '尚未举办'}</p><ul>{def.goals.map(g => <li key={g}>{g}</li>)}</ul><button className="secondary-button" disabled={!available || Boolean(pet.timePause)} onClick={() => update(p => beginMuseumCuration(p, id))}>{available ? '举办这个主题' : '继续收集展品与解锁料理'}</button></article>; })}</div>
    </> : <>
      <section className="museum-card"><div className="museum-section-heading"><h2>{museumThemes[draft.theme].name}</h2><button className="secondary-button" disabled={Boolean(pet.timePause)} onClick={() => update(p => cancelMuseumCuration(p, draft.id))}>取消本场筹备</button></div><p>筹备自动保存，跨周也可以接着布置。评分只看搭配，展览规模决定累计策展星。</p><ol className="museum-goals">{museumThemes[draft.theme].goals.map((goal, i) => <li key={goal} className={quote.goals[i] ? 'is-ready' : ''}>{quote.goals[i] ? <Check size={18} /> : <Star size={18} />}<span>{goal}</span></li>)}</ol></section>
      <section className="museum-card"><h3>选择展览规模</h3><div className="museum-scale-grid">{Object.entries(museumScales).map(([key, scale]) => <button key={key} type="button" aria-pressed={draft.scale === key} className={draft.scale === key ? 'is-selected' : ''} onClick={() => change({ scale: key as MuseumScale })}><strong>{scale.name}</strong><span>{formatInteger(scale.coins)} 金币＋{scale.apples} 金苹果</span><small>两种料理各 {scale.portions} 份 · 策展星 ×{scale.coefficient}</small></button>)}</div></section>
      <section className="museum-card"><h3>布置展品 · {draft.exhibits.length} / 3</h3><div className="museum-exhibit-grid">{owned.map(e => { const selected = draft.exhibits.includes(e.id); return <button key={e.id} className={`museum-exhibit${selected ? ' is-selected' : ''}`} aria-pressed={selected} disabled={!selected && draft.exhibits.length >= 3} onClick={() => change({ exhibits: selected ? draft.exhibits.filter(id => id !== e.id) : [...draft.exhibits, e.id] })}><img src={museumExhibitImage(e.id, icons)} alt="" /><strong>{e.name}</strong><small>{museumTagNames[e.tags[0]]}{e.tags.slice(1).map(tag => ` · ${museumTagNames[tag]}`)}</small><span>{selected ? '已选入展览' : e.quest ? '委托收藏' : '展厅收藏'}</span></button>; })}</div></section>
      <section className="museum-card"><h3>准备两种料理</h3><label className="museum-search">查找料理<input type="search" placeholder="输入料理名称" value={filter} onChange={e => setFilter(e.target.value)} /></label><div className="museum-menu">{[0, 1].map(index => <label key={index}>料理 {index + 1}<select disabled={index === 1 && !draft.dishes[0]} value={draft.dishes[index] ?? ''} onChange={e => { const next = [...draft.dishes]; if (e.target.value) next[index] = e.target.value; else next.splice(index, 1); change({ dishes: next.filter(Boolean) }); }}><option value="">请选择料理</option>{dishes.filter(d => filteredDishes.includes(d) || draft.dishes.includes(d.id)).map(d => <option key={d.id} value={d.id} disabled={draft.dishes.some((id, i) => i !== index && id === d.id)}>{dishName(d.id)} · 库存 {formatInteger(pet.inventory[d.id] ?? 0)}</option>)}</select><small>需要 {quote.cost.portions} 份{draft.dishes[index] ? `，现有 ${formatInteger(pet.inventory[draft.dishes[index]] ?? 0)} 份` : ''}</small></label>)}</div></section>
      <section className="museum-card museum-host"><div><h3>本场评分 {quote.rating} / 3 星</h3><p>累计策展星 +{quote.stars} · {formatInteger(quote.cost.coins)} 金币＋{quote.cost.apples} 金苹果</p><small>{quote.reason || '方案和物资已备齐，可以邀请邻居。'}</small></div><button className="primary-button" disabled={Boolean(quote.reason)} onClick={() => setConfirm(true)}>预览并举办</button></section>
      {confirm && <DialogShell role="alertdialog" className="museum-dialog museum-confirm-dialog" labelId="museum-host-title" onClose={() => setConfirm(false)}><header><h2 id="museum-host-title">举办「{museumThemes[draft.theme].name}」</h2></header><div className="museum-dialog-body"><p>{quote.cost.name} · 评分 {quote.rating} 星 · 获得 {quote.stars} 策展星</p><p>消耗 {formatInteger(quote.cost.coins)} 金币、{quote.cost.apples} 个金苹果，以及{draft.dishes.map(d => `${dishName(d)} ×${quote.cost.portions}`).join('、')}。</p><p>展品会留在收藏中，结束后新增本场纪念与访客留言。</p>{quote.reason && <p role="status">{quote.reason}</p>}</div><footer><button className="secondary-button" onClick={() => setConfirm(false)}>继续布置</button><button className="primary-button" disabled={Boolean(quote.reason)} onClick={() => { update(p => hostMuseumCuration(p, draft.id, draft.revision, actorId, actorName, getNeighborIdentities(mods, actorId))); setConfirm(false); }}>确认举办</button></footer></DialogShell>}
    </>}
  </section>;
};
