import type { RecipeDefinition } from './kitchenRecipes';
import type { NewRecipeId, CookingMethod } from './companionActivityTypes';
import type { BuiltinItemId } from './petTypes';
import type { FoodRarity } from './foodCatalog';

const dish = (id: NewRecipeId, name: string, category: RecipeDefinition['category'], rarity: FoodRarity, ingredients: BuiltinItemId[], hunger: number, energy: number, mood: number, chainHearts: number, method: CookingMethod = 'pan'): RecipeDefinition => ({
  id, name, en: name, category, rarity, demand: rarity === 'epic' || rarity === 'legendary' ? 'premium' : rarity === 'rare' ? 'specialty' : 'basic', ingredients,
  method, glyph: id === 'valley_travel_bento' ? '🍱' : ({ main: '🍚', side: '🍽️', soup: '🍲', dessert: '🍰', drink: '🍵' })[category],
  effect: { hunger, energy, mood }, chainHearts, main: category === 'main', ...(category === 'soup' ? { technique: 'simmer' as const } : {}),
});
const snack = (recipe: RecipeDefinition, fixedProcessingProfit: number, glyph: string): RecipeDefinition => ({ ...recipe, fixedProcessingProfit, glyph });
export const expandedRecipes: readonly RecipeDefinition[] = [
  dish('mashed_potato', '奶油土豆泥', 'side', 'rare', ['potato', 'cream'], 36, 36, 18, 2),
  dish('corn_chowder', '田园玉米浓汤', 'soup', 'fine', ['sweet_corn', 'farm_milk'], 22, 28, 18, 2),
  dish('pumpkin_rice', '南瓜炖饭', 'main', 'fine', ['pumpkin', 'rice', 'wild_onion'], 48, 32, 14, 2),
  dish('pepper_pork_bowl', '甜椒肉末盖饭', 'main', 'rare', ['sweet_pepper', 'pork', 'dish_plain_rice'], 62, 38, 14, 3),
  dish('bamboo_mushroom_soup', '笋菇鲜汤', 'soup', 'fine', ['bamboo_shoot', 'valley_mushroom', 'creek_herb'], 18, 30, 12, 2),
  dish('lotus_pork_soup', '莲藕暖肉汤', 'soup', 'rare', ['lotus_root', 'pork', 'ginger'], 26, 40, 16, 3),
  dish('chestnut_rice', '山栗焖饭', 'main', 'rare', ['mountain_chestnut', 'rice'], 46, 40, 14, 2),
  dish('cream_matsutake', '奶油煎松茸', 'side', 'epic', ['matsutake', 'cream'], 42, 120, 50, 6),
  dish('cheese_vegetables', '奶酪焗蔬菜', 'side', 'rare', ['potato', 'greens', 'cheese'], 44, 50, 28, 3, 'oven'),
  dish('wood_ear_dumplings', '木耳白菜素饺', 'main', 'fine', ['wood_ear', 'cabbage', 'flour'], 50, 30, 18, 2),
  dish('crispy_wheat_fish', '香酥麦穗鱼', 'side', 'common', ['wheat_fish', 'flour'], 28, 22, 12, 1),
  dish('tomato_crucian', '番茄鲫鱼煲', 'soup', 'fine', ['pond_crucian', 'tomato', 'ginger'], 24, 34, 14, 2),
  dish('lemon_trout', '柠檬香煎鳟鱼', 'side', 'rare', ['stream_trout', 'wild_lemon', 'cooking_oil'], 34, 44, 22, 3),
  dish('pumpkin_perch_soup', '南瓜鲈鱼浓汤', 'soup', 'rare', ['river_perch', 'pumpkin', 'farm_milk'], 26, 42, 18, 3),
  dish('bamboo_grouper', '笋香清蒸溪石斑', 'side', 'rare', ['stream_grouper', 'bamboo_shoot', 'ginger'], 32, 40, 18, 3),
  dish('pepper_redtail', '甜椒赤尾烤鱼', 'side', 'epic', ['redtail_barbel', 'sweet_pepper', 'creek_herb'], 38, 54, 24, 4),
  dish('herb_catfish', '香草烤鲶鱼', 'side', 'fine', ['striped_catfish', 'creek_herb'], 32, 34, 16, 2),
  dish('corn_bream_soup', '玉米鳊鱼汤', 'soup', 'rare', ['moss_bream', 'sweet_corn'], 22, 38, 18, 2),
  dish('honey_eel_rice', '蜜烤鳗鱼饭', 'main', 'epic', ['glass_eel', 'hill_honey', 'dish_plain_rice'], 82, 70, 30, 4),
  dish('sardine_rice_ball', '海藻沙丁饭团', 'main', 'fine', ['silver_sardine', 'coast_kelp', 'dish_plain_rice'], 64, 46, 16, 2),
  dish('salt_mackerel', '盐烤青花鲭鱼', 'side', 'rare', ['blue_mackerel', 'sea_salt'], 34, 42, 16, 2),
  dish('lemon_bream_rice', '柠香鲷鱼烩饭', 'main', 'epic', ['bluefin_bream', 'wild_lemon', 'dish_plain_rice'], 68, 76, 30, 4),
  dish('strawberry_cheese_cup', '草莓奶酪杯', 'dessert', 'rare', ['strawberry', 'cheese'], 28, 44, 48, 3, 'mix'),
  dish('berry_jam_biscuit', '林莓果酱饼', 'dessert', 'rare', ['forest_berry_jam', 'flour', 'egg'], 40, 40, 42, 3, 'oven'),
  dish('honey_pumpkin_pie', '蜂蜜南瓜派', 'dessert', 'rare', ['pumpkin', 'hill_honey', 'flour'], 44, 38, 38, 3, 'oven'),
  dish('chestnut_milk_cake', '山栗鲜奶糕', 'dessert', 'rare', ['mountain_chestnut', 'farm_milk', 'glutinous_rice'], 44, 42, 40, 3),
  dish('mint_lemon_drink', '薄荷柠檬饮', 'drink', 'fine', ['mint', 'wild_lemon'], 8, 26, 26, 2, 'mix'),
  dish('lotus_milk_soup', '莲子鲜奶羹', 'soup', 'rare', ['lotus_seed', 'farm_milk'], 16, 34, 28, 2),
  dish('pine_honey_biscuit', '松子蜂蜜饼', 'dessert', 'rare', ['pine_nut', 'hill_honey', 'flour'], 38, 40, 36, 3, 'oven'),
  dish('mountain_herb_tea', '高山香草茶', 'drink', 'epic', ['mountain_tea', 'creek_herb'], 12, 112, 60, 6, 'mix'),
  dish('seafood_rice', '蛤蜊海虾烩饭', 'main', 'rare', ['clam', 'sea_shrimp', 'dish_plain_rice'], 66, 56, 24, 3),
  dish('valley_travel_bento', '溪谷远行便当', 'main', 'legendary', ['dish_chestnut_rice', 'dish_bamboo_mushroom_soup', 'egg'], 78, 84, 32, 6, 'mix'),
  dish('highland_potato_stew', '高山薯暖肉煲', 'soup', 'rare', ['highland_potato', 'pork', 'wild_onion'], 44, 56, 18, 3),
  dish('snow_bean_rice', '雪原豆蛋盖饭', 'main', 'rare', ['snow_bean', 'dish_plain_rice', 'egg'], 70, 50, 20, 3),
  dish('honey_milk', '蜂蜜暖奶', 'drink', 'rare', ['hill_honey', 'farm_milk'], 18, 48, 34, 3, 'mix'),
  dish('highland_potato_gratin', '香菇奶酪焗高山薯', 'side', 'epic', ['highland_potato', 'cheese', 'shiitake'], 64, 60, 28, 4, 'oven'),
  dish('snow_bean_soup', '雪豆香草汤', 'soup', 'rare', ['snow_bean', 'carrot', 'creek_herb'], 26, 46, 14, 3),
  dish('summit_travel_bento', '山顶守夜便当', 'main', 'legendary', ['dish_snow_bean_rice', 'braised_pork', 'pine_nut'], 118, 98, 38, 6, 'mix'),
  dish('lotus_wood_ear', '木耳莲藕小炒', 'side', 'rare', ['wood_ear', 'lotus_root', 'cooking_oil'], 30, 36, 14, 3),
  dish('lotus_pumpkin_porridge', '莲子南瓜粥', 'soup', 'rare', ['lotus_seed', 'pumpkin', 'rice'], 32, 38, 16, 3),
  dish('mint_watermelon_cup', '薄荷西瓜杯', 'drink', 'fine', ['watermelon', 'mint'], 8, 24, 18, 2, 'mix'),
  dish('orange_nut_shake', '香橙坚果奶昔', 'drink', 'fine', ['orange', 'mixed_nuts', 'farm_milk'], 20, 28, 34, 2, 'blender'),
  dish('berry_jam_shake', '林莓果酱奶昔', 'drink', 'rare', ['forest_berry_jam', 'farm_milk'], 16, 38, 42, 3, 'blender'),
  dish('double_berry_cup', '草莓林莓果杯', 'dessert', 'fine', ['strawberry', 'forest_berry'], 28, 20, 38, 2, 'mix'),
  dish('lotus_trotter_soup', '莲藕猪蹄汤', 'soup', 'epic', ['pig_trotter', 'lotus_root', 'ginger'], 36, 58, 18, 4),
  dish('matsutake_clear_soup', '松茸清汤', 'soup', 'epic', ['matsutake', 'bamboo_shoot'], 18, 112, 32, 6),
  dish('honey_milk_tea', '蜂蜜高山奶茶', 'drink', 'epic', ['hill_honey', 'mountain_tea', 'farm_milk'], 22, 104, 84, 6, 'mix'),
  dish('sunflower_nut_crisp', '葵香坚果脆饼', 'dessert', 'rare', ['sunflower_kernel', 'mixed_nuts', 'flour'], 38, 30, 38, 3, 'oven'),
  dish('ginger_carp', '葱姜鲤鱼', 'side', 'fine', ['pond_carp', 'wild_onion', 'ginger'], 34, 32, 14, 2),
  dish('wheat_fish_custard', '麦穗鱼蛋羹', 'soup', 'fine', ['wheat_fish', 'egg'], 18, 26, 14, 2),
  dish('pan_seared_perch', '香煎鲈鱼', 'side', 'rare', ['river_perch', 'cooking_oil'], 38, 40, 20, 3),
  dish('grouper_porridge', '石斑青菜粥', 'soup', 'rare', ['stream_grouper', 'greens', 'rice'], 24, 44, 12, 3),
  { ...dish('redtail_rice', '赤尾鱼焖饭', 'main', 'epic', ['redtail_barbel', 'rice', 'wild_onion'], 78, 62, 18, 4), technique: 'simmer' },
  { ...dish('catfish_rice', '番茄鲶鱼焖饭', 'main', 'fine', ['striped_catfish', 'rice', 'tomato'], 62, 42, 12, 2), technique: 'simmer' },
  dish('ginger_bream', '姜香煎鳊鱼', 'side', 'rare', ['moss_bream', 'ginger', 'cooking_oil'], 38, 48, 16, 3),
  dish('eel_mushroom_soup', '香菇鳗鱼暖汤', 'soup', 'epic', ['glass_eel', 'shiitake', 'ginger'], 26, 64, 20, 4),
  { ...dish('tomato_sardine', '番茄炖沙丁鱼', 'side', 'fine', ['silver_sardine', 'tomato'], 32, 38, 18, 2), technique: 'simmer' },
  dish('mackerel_rice', '青花鲭鱼饭', 'main', 'rare', ['blue_mackerel', 'dish_plain_rice', 'sea_salt'], 68, 48, 14, 3),
  { ...dish('steamed_bluefin', '清蒸蓝鳍鲷', 'side', 'epic', ['bluefin_bream', 'ginger'], 36, 66, 24, 4), technique: 'simmer' },
  dish('clam_kelp_soup', '蛤蜊海藻汤', 'soup', 'rare', ['clam', 'coast_kelp', 'ginger'], 16, 42, 14, 3),
  dish('shrimp_eggs', '海虾滑蛋', 'side', 'rare', ['sea_shrimp', 'egg'], 34, 42, 20, 3),
  dish('apple_orange_juice', '苹果香橙汁', 'drink', 'fine', ['apple', 'orange'], 12, 26, 24, 2, 'blender'),
  dish('strawberry_watermelon_juice', '草莓西瓜汁', 'drink', 'fine', ['strawberry', 'watermelon'], 12, 24, 34, 2, 'blender'),
  dish('berry_lemon_juice', '林莓柠檬汁', 'drink', 'rare', ['forest_berry', 'wild_lemon', 'mint'], 10, 32, 32, 3, 'blender'),
  dish('banana_strawberry_juice', '香蕉草莓汁', 'drink', 'fine', ['banana', 'strawberry'], 18, 30, 30, 2, 'blender'),
  { ...dish('carrot_apple_orange_juice', '胡萝卜苹果橙汁', 'drink', 'rare', ['carrot', 'apple', 'orange'], 16, 34, 22, 3, 'blender'), effect: { hunger: 16, energy: 34, mood: 22, health: 8 } },
  { ...dish('herb_trout_soup', '香草鳟鱼汤', 'soup', 'rare', ['stream_trout', 'creek_herb', 'wild_onion'], 20, 44, 14, 3), effect: { hunger: 20, energy: 44, mood: 14, health: 12 } },
  { ...dish('herb_perch_soup', '香草鲈鱼汤', 'soup', 'rare', ['river_perch', 'creek_herb', 'ginger'], 22, 46, 16, 3), effect: { hunger: 22, energy: 46, mood: 16, health: 14 } },
  { ...dish('herb_bluefin_soup', '香草鲷鱼汤', 'soup', 'epic', ['bluefin_bream', 'creek_herb', 'shiitake'], 26, 78, 28, 4), effect: { hunger: 26, energy: 78, mood: 28, health: 18 } },
  snack(dish('flatbread', '薄饼', 'main', 'common', ['flour'], 18, 8, 2, 0), 4, '🫓'),
  { ...snack(dish('tomato_ketchup', '番茄酱', 'side', 'common', ['tomato'], 4, 2, 4, 0), 3, '🍅'), technique: 'simmer' },
  snack(dish('french_fries', '薯条', 'side', 'common', ['potato', 'cooking_oil'], 28, 18, 16, 1), 26, '🍟'),
  snack(dish('ketchup_fries', '番茄酱薯条', 'side', 'fine', ['dish_french_fries', 'dish_tomato_ketchup'], 34, 20, 20, 2, 'mix'), 17, '🍟'),
  snack(dish('egg_wrap', '鸡蛋卷饼', 'main', 'fine', ['dish_flatbread', 'dish_carrot_omelet'], 52, 30, 16, 2, 'mix'), 19, '🌯'),
  snack(dish('tomato_egg_wrap', '番茄鸡蛋卷饼', 'main', 'fine', ['dish_egg_wrap', 'dish_tomato_ketchup'], 56, 32, 20, 3, 'mix'), 17, '🌯'),
  snack(dish('red_bean_wrap', '豆沙薄饼卷', 'dessert', 'fine', ['dish_flatbread', 'red_bean_paste'], 40, 22, 24, 2, 'mix'), 28, '🫓'),
  snack(dish('wrap_fries_set', '卷饼薯条套餐', 'main', 'fine', ['dish_egg_wrap', 'dish_ketchup_fries'], 90, 48, 36, 5, 'mix'), 30, '🍱'),
  { ...snack(dish('fish_fries_set', '鱼薯果汁套餐', 'main', 'fine', ['dish_crispy_wheat_fish', 'dish_ketchup_fries', 'dish_carrot_apple_orange_juice'], 80, 64, 44, 8, 'mix'), 30, '🍱'), effect: { hunger: 80, energy: 64, mood: 44, health: 8 } },
  snack(dish('corn_fritter', '玉米烙', 'side', 'fine', ['sweet_corn', 'flour', 'egg'], 32, 24, 18, 2), 26, '🌽'),
  snack(dish('cheesy_corn_fritter', '奶酪玉米烙', 'side', 'fine', ['dish_corn_fritter', 'cheese'], 44, 34, 28, 3, 'oven'), 20, '🧀'),
  snack(dish('pumpkin_rice_cake', '南瓜糯米饼', 'dessert', 'fine', ['pumpkin', 'glutinous_rice'], 38, 22, 24, 2), 26, '🥞'),
  snack(dish('red_bean_pumpkin_cake', '豆沙南瓜饼', 'dessert', 'fine', ['dish_pumpkin_rice_cake', 'red_bean_paste'], 48, 28, 32, 3), 20, '🥞'),
  snack(dish('potato_cake', '香煎土豆饼', 'side', 'fine', ['dish_mashed_potato', 'flour'], 44, 34, 20, 3), 24, '🥔'),
  snack(dish('garden_vegetable_wrap', '田园蔬菜卷', 'main', 'fine', ['dish_flatbread', 'cabbage', 'sweet_pepper', 'wood_ear'], 46, 28, 20, 2), 24, '🌯'),
  snack(dish('berry_jam_wrap', '林莓果酱卷', 'dessert', 'fine', ['dish_flatbread', 'forest_berry_jam'], 34, 24, 34, 2, 'mix'), 24, '🫓'),
  snack(dish('pan_fried_dumplings', '香煎饺子', 'main', 'fine', ['dish_dumplings_pork_cabbage', 'cooking_oil'], 64, 36, 20, 3), 24, '🥟'),
];
