import type { DishId } from './core/companionActivityTypes';

// Lower rim offsets use each approved 256 px master silhouette at the ornament columns.
// Bowls, cups, trays and boxes keep their own vessels and do not receive plate ornaments.
export const newDishPresentation = {
  dish_mushroom_rice: { container: 'fixed_plate', rimBottom: '29.30%' },
  dish_honey_drink: { container: 'fixed_glass', rimBottom: '19.14%' },
  dish_berry_milk: { container: 'fixed_glass', rimBottom: '17.97%' },
  dish_kelp_rice: { container: 'fixed_plate', rimBottom: '27.34%' },
  dish_herb_porridge: { container: 'fixed_bowl', rimBottom: '23.44%' },
  dish_creek_fish_soup: { container: 'fixed_bowl', rimBottom: '26.17%' },
  dish_river_grill: { container: 'fixed_plate', rimBottom: '28.13%' },
  dish_milk_custard: { container: 'fixed_bowl', rimBottom: '22.66%' },
  dish_carp_rice: { container: 'fixed_plate', rimBottom: '26.56%' },
  dish_mashed_potato: { container: 'fixed_plate', rimBottom: '26.17%' },
  dish_corn_chowder: { container: 'fixed_bowl', rimBottom: '25.39%' },
  dish_pumpkin_rice: { container: 'fixed_plate', rimBottom: '25.78%' },
  dish_pepper_pork_bowl: { container: 'fixed_plate', rimBottom: '25.39%' },
  dish_bamboo_mushroom_soup: { container: 'fixed_bowl', rimBottom: '25.00%' },
  dish_lotus_pork_soup: { container: 'fixed_bowl', rimBottom: '25.00%' },
  dish_chestnut_rice: { container: 'fixed_plate', rimBottom: '25.78%' },
  dish_cream_matsutake: { container: 'fixed_plate', rimBottom: '25.78%' },
  dish_cheese_vegetables: { container: 'fixed_baking_dish', rimBottom: '25.00%' },
  dish_wood_ear_dumplings: { container: 'fixed_plate', rimBottom: '24.61%' },
  dish_crispy_wheat_fish: { container: 'fixed_plate', rimBottom: '25.00%' },
  dish_tomato_crucian: { container: 'fixed_bowl', rimBottom: '25.39%' },
  dish_lemon_trout: { container: 'fixed_plate', rimBottom: '27.73%' },
  dish_pumpkin_perch_soup: { container: 'fixed_bowl', rimBottom: '23.05%' },
  dish_bamboo_grouper: { container: 'fixed_plate', rimBottom: '27.73%' },
  dish_pepper_redtail: { container: 'fixed_plate', rimBottom: '25.00%' },
  dish_herb_catfish: { container: 'fixed_plate', rimBottom: '26.17%' },
  dish_corn_bream_soup: { container: 'fixed_bowl', rimBottom: '21.48%' },
  dish_honey_eel_rice: { container: 'fixed_plate', rimBottom: '25.39%' },
  dish_sardine_rice_ball: { container: 'fixed_plate', rimBottom: '23.83%' },
  dish_salt_mackerel: { container: 'fixed_plate', rimBottom: '26.95%' },
  dish_lemon_bream_rice: { container: 'fixed_plate', rimBottom: '25.78%' },
  dish_strawberry_cheese_cup: { container: 'fixed_dessert_glass', rimBottom: '17.97%' },
  dish_berry_jam_biscuit: { container: 'fixed_plate', rimBottom: '23.83%' },
  dish_honey_pumpkin_pie: { container: 'fixed_plate', rimBottom: '23.44%' },
  dish_chestnut_milk_cake: { container: 'fixed_plate', rimBottom: '25.78%' },
  dish_mint_lemon_drink: { container: 'fixed_glass', rimBottom: '17.97%' },
  dish_lotus_milk_soup: { container: 'fixed_bowl', rimBottom: '23.44%' },
  dish_pine_honey_biscuit: { container: 'fixed_plate', rimBottom: '26.95%' },
  dish_mountain_herb_tea: { container: 'fixed_glass', rimBottom: '19.92%' },
  dish_seafood_rice: { container: 'fixed_plate', rimBottom: '23.83%' },
  dish_valley_travel_bento: { container: 'fixed_box', rimBottom: '17.19%' },
} satisfies Partial<Record<DishId, { container: string; rimBottom: string }>>;
